name: giveway_mobile
description: GiveWay — Adaptive Traffic Equity System (Flutter Mobile App)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  web_socket_channel: ^3.0.0
  shared_preferences: ^2.3.0
  fl_chart: ^0.70.0
  google_fonts: ^6.2.0
  mobile_scanner: ^6.0.0
  showcaseview: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
